# Generated by Django 4.2.3 on 2023-11-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader_name', models.CharField(max_length=30)),
                ('uploader_last', models.CharField(max_length=30)),
                ('uploader_add', models.CharField(max_length=40)),
                ('uploader_type', models.CharField(max_length=35)),
                ('uploader_img', models.ImageField(blank=True, upload_to='uploader')),
            ],
        ),
    ]
